title: tdivyajyotis.in
description: Tripathy Divyajyoti Senapati
baseurl: /
url: https://tdivyajyotis.in


exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
